spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_review
    username: your_username
    password: your_password
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  messages:
    encoding: UTF-8

server:
  servlet:
    context-path: /api/v1
  port: 9099